name: Deploy Maven App to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to your version

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare artifact
        run: |
          mkdir -p build
          cp target/*.jar build/app.jar
          ls -l build

      - name: Copy artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/app.jar"
          target: "/home/${{ secrets.EC2_USER }}/app/"

      - name: Deploy and restart app on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/app
            echo "Stopping old app..."
            pkill -f 'java -jar' || true
            echo "Starting new app..."
            nohup java -jar app.jar > app.log 2>&1 &
            echo "Deployment successful."
